// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/blog" | "/blog/[slug]" | "/contact" | "/dashboard" | "/dashboard/billing" | "/dashboard/reader" | "/dashboard/tools" | "/onboarding" | "/privacy" | "/terms"
type AppRouteHandlerRoutes = "/api/billing/checkout" | "/api/billing/portal" | "/api/credits" | "/api/extension-import" | "/api/extension-import/[id]" | "/api/extension-notes" | "/api/extension-token" | "/api/extension-tts" | "/api/extension-vault" | "/api/extract" | "/api/jobs" | "/api/jobs/[id]" | "/api/parse" | "/api/reader-docs" | "/api/tracks" | "/api/tracks/[id]" | "/api/tracks/[id]/audio" | "/api/tts" | "/api/webhooks/stripe"
type PageRoutes = "/404" | "/500"
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/404": {}
  "/500": {}
  "/api/billing/checkout": {}
  "/api/billing/portal": {}
  "/api/credits": {}
  "/api/extension-import": {}
  "/api/extension-import/[id]": { "id": string; }
  "/api/extension-notes": {}
  "/api/extension-token": {}
  "/api/extension-tts": {}
  "/api/extension-vault": {}
  "/api/extract": {}
  "/api/jobs": {}
  "/api/jobs/[id]": { "id": string; }
  "/api/parse": {}
  "/api/reader-docs": {}
  "/api/tracks": {}
  "/api/tracks/[id]": { "id": string; }
  "/api/tracks/[id]/audio": { "id": string; }
  "/api/tts": {}
  "/api/webhooks/stripe": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/contact": {}
  "/dashboard": {}
  "/dashboard/billing": {}
  "/dashboard/reader": {}
  "/dashboard/tools": {}
  "/onboarding": {}
  "/privacy": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
