// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/reader/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reader">> = Specific
  const handler = {} as typeof import("../../app/dashboard/reader/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/tools">> = Specific
  const handler = {} as typeof import("../../app/dashboard/tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/checkout">> = Specific
  const handler = {} as typeof import("../../app/api/billing/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/portal">> = Specific
  const handler = {} as typeof import("../../app/api/billing/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/credits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/credits">> = Specific
  const handler = {} as typeof import("../../app/api/credits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/extension-import/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/extension-import/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/extension-import/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/extension-import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/extension-import">> = Specific
  const handler = {} as typeof import("../../app/api/extension-import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/extension-notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/extension-notes">> = Specific
  const handler = {} as typeof import("../../app/api/extension-notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/extension-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/extension-token">> = Specific
  const handler = {} as typeof import("../../app/api/extension-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/extension-tts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/extension-tts">> = Specific
  const handler = {} as typeof import("../../app/api/extension-tts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/extension-vault/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/extension-vault">> = Specific
  const handler = {} as typeof import("../../app/api/extension-vault/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/extract/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/extract">> = Specific
  const handler = {} as typeof import("../../app/api/extract/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/jobs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/jobs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs">> = Specific
  const handler = {} as typeof import("../../app/api/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/parse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/parse">> = Specific
  const handler = {} as typeof import("../../app/api/parse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reader-docs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reader-docs">> = Specific
  const handler = {} as typeof import("../../app/api/reader-docs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tracks/[id]/audio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tracks/[id]/audio">> = Specific
  const handler = {} as typeof import("../../app/api/tracks/[id]/audio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tracks/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tracks/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/tracks/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tracks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tracks">> = Specific
  const handler = {} as typeof import("../../app/api/tracks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tts">> = Specific
  const handler = {} as typeof import("../../app/api/tts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/stripe">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
