import { Brain } from "lucide-react";
import Link from "next/link";
import Footer from "@/components/Footer";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#080a0c] text-neutral-300 flex flex-col justify-between">
      <div className="max-w-3xl mx-auto space-y-12 py-16 px-4 flex-1">
        <header className="space-y-4">
          <Link href="/" className="inline-flex items-center gap-2 text-indigo-400 hover:text-indigo-300 transition-colors">
            <Brain className="h-5 w-5" />
            <span className="font-bold tracking-tight text-white">Hyperfi</span>
          </Link>
          <h1 className="text-4xl font-extrabold text-white tracking-tight">Terms of Service</h1>
          <p className="text-neutral-500">Last updated: July 2026</p>
        </header>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">1. Acceptance of Terms</h2>
          <p>
            By accessing and using Hyperfi, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use our service.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">2. Use License</h2>
          <p>
            We grant you a personal, non-transferable, non-exclusive license to use the audio tracks generated by Hyperfi for your personal or commercial use, provided you comply with our Acceptable Use Policy and do not use the service to generate harmful, illegal, or abusive content.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">3. Credits and Billing</h2>
          <p>
            Hyperfi operates on a credit-based system. Credits are consumed based on the character length of the text you submit. Paid plans are billed on a recurring basis. You may cancel your subscription at any time. When you cancel, your cancellation will take effect on your next billing date. You will continue to have access to your plan's features and credits until that date.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">4. Refund Policy</h2>
          <p>
            All purchases are final. <strong>We do not offer refunds</strong> for any payments made. If you choose to cancel your subscription, it will automatically terminate at the end of your current billing cycle, and no further charges will be applied. Refunds will not be provided for partially unused billing periods, unused credits, or accidental sign-ups.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">5. Service Availability</h2>
          <p>
            While we strive for 100% uptime, Hyperfi is provided &quot;as is&quot; and we make no warranties regarding the continuous availability of the service. We rely on third-party APIs (such as ElevenLabs) which may experience outages beyond our control.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">6. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your account at any time, without prior notice, if you violate these Terms of Service or engage in fraudulent or abusive behavior.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">7. Changes to Terms</h2>
          <p>
            We may update these terms occasionally. We will notify users of any material changes. Continued use of the service after such changes constitutes acceptance of the new terms.
          </p>
        </section>
      </div>
      <Footer />
    </div>
  );
}
